-- MySQL Script generated by MySQL Workbench
-- Tue Dec 15 18:34:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema private_school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema private_school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `private_school` DEFAULT CHARACTER SET utf8 ;
USE `private_school` ;

-- -----------------------------------------------------
-- Table `private_school`.`Trainers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_school`.`Trainers` (
  `trainer_id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `Subject` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`trainer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_school`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_school`.`Courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `stream` VARCHAR(10) NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `startdate` DATE NOT NULL,
  `enddate` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_school`.`Assignments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_school`.`Assignments` (
  `assignment_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `subDateTime` DATETIME NOT NULL,
  PRIMARY KEY (`assignment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_school`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_school`.`Students` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `dob` DATE NOT NULL,
  `tuitionFees` DOUBLE NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_school`.`Students_Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_school`.`Students_Courses` (
  `enrollment_id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `Course_id` INT NOT NULL,
  PRIMARY KEY (`enrollment_id`),
  INDEX `fk_Students_has_Courses_Courses1_idx` (`Course_id` ASC) VISIBLE,
  INDEX `fk_Students_has_Courses_Students_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_Students_Courses_Students`
    FOREIGN KEY (`student_id`)
    REFERENCES `private_school`.`Students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Courses_Courses`
    FOREIGN KEY (`Course_id`)
    REFERENCES `private_school`.`Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_school`.`Assignments_Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_school`.`Assignments_Courses` (
  `Course_id` INT NOT NULL,
  `assignment_id` INT NOT NULL,
  PRIMARY KEY (`Course_id`, `assignment_id`),
  INDEX `fk_Courses_has_Assignments_Assignments1_idx` (`assignment_id` ASC) VISIBLE,
  INDEX `fk_Courses_has_Assignments_Courses1_idx` (`Course_id` ASC) VISIBLE,
  CONSTRAINT `fk_Assignments_Courses_Courses`
    FOREIGN KEY (`Course_id`)
    REFERENCES `private_school`.`Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Assignments_Courses_Assignments`
    FOREIGN KEY (`assignment_id`)
    REFERENCES `private_school`.`Assignments` (`assignment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_school`.`AssignmentperCourseperStudent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_school`.`AssignmentperCourseperStudent` (
  `enrollment_id` INT NOT NULL,
  `assignment_id` INT NOT NULL,
  `oralMark` INT NULL,
  `totalMark` INT NULL,
  PRIMARY KEY (`enrollment_id`, `assignment_id`),
  INDEX `fk_Students_Courses_has_Assignments_Assignments1_idx` (`assignment_id` ASC) VISIBLE,
  INDEX `fk_Students_Courses_has_Assignments_Students_Courses1_idx` (`enrollment_id` ASC) VISIBLE,
  CONSTRAINT `fk_AssignmentperCourseperStudent_Students_Courses`
    FOREIGN KEY (`enrollment_id`)
    REFERENCES `private_school`.`Students_Courses` (`enrollment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SAssignmentperCourseperStudent_Assignments`
    FOREIGN KEY (`assignment_id`)
    REFERENCES `private_school`.`Assignments` (`assignment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_school`.`Trainers_Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_school`.`Trainers_Courses` (
  `trainer_id` INT NOT NULL,
  `Course_id` INT NOT NULL,
  PRIMARY KEY (`trainer_id`, `Course_id`),
  INDEX `fk_Trainers_has_Courses_Courses1_idx` (`Course_id` ASC) VISIBLE,
  INDEX `fk_Trainers_has_Courses_Trainers1_idx` (`trainer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Trainers_Courses_Trainers`
    FOREIGN KEY (`trainer_id`)
    REFERENCES `private_school`.`Trainers` (`trainer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trainers_Courses_Courses`
    FOREIGN KEY (`Course_id`)
    REFERENCES `private_school`.`Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
